### ISSUE TITLE
command 'sync-rsync.syncUp' not found

### ISSUE THREAD

**Issue by miaulalala** [thisboyiscrazy/vscode-rsync#69]
Same for all other commands. Used to work fine up until today.

Used to have "sync.rsync.options", now it won't accept that config any more and the whole extension is bust.

My sync-rsync config:

    "sync-rsync.local": "/Users/xxx/xxx/webapp/",
    "sync-rsync.remote": "root@xxx:/var/www/html/webapp/",
    "sync-rsync.onSave": true,    
    "sync-rsync.showProgress" : true,
    "sync-rsync.autoShowOutput": true,
    "sync-rsync.executableShell": "/bin/bash",
    "sync-rsync.options": 
    [
        [ "verbose" ],
        [ "ignore-times" ],
        [ "progress" ],
        [ "itemize-changes" ],
        [ "times" ]
    ]

**Comment by thisboyiscrazy** [comment]
I just tried your setting on Linux with version 0.34.2. and it seems to work.

It looks like you are using Linux, can you verify you are using 0.34.2?

**Comment by miaulalala** [comment]
I'm using MacOS, and it's Version 0.34.2.

**Comment by thisboyiscrazy** [comment]
Thanks, i will try it on my mac mini.

**Comment by thisboyiscrazy** [comment]
I tested on a mac mini using your settings. The first time I launched Visual Studio Code the extension had an error. But I could not replicate it from there. Can you try uninstalling and reinstalling the extension?

If you are still having a problem can you look in "Log (Extension Host)" and post anything related to "vscode-ext.sync-rsync"

**Comment by miaulalala** [comment]
Hi, so I uninstalled and reinstalled the extension as you asked. The output for the Extension log is as follows:

```
[Extension Host] Here is the error stack:  TypeError: util_1.promisify is not a function
	at Object.<anonymous> (/Users/alarch/.vscode/extensions/vscode-ext.sync-rsync-0.34.2/out/src/extension.js:21:28)
	at Object.<anonymous> (/Users/alarch/.vscode/extensions/vscode-ext.sync-rsync-0.34.2/out/src/extension.js:422:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:653:398)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js:30:770)
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:676:131
	at t._doActivateExtension (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:676:243)
	at t._activateExtension (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:675:161)
	at Object.actualActivateExtension (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:282)
	at e._activateExtension (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:920)
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:539
	at Array.map (native)
	at e._activateExtensions (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:417:514)
	at e.activateByEvent (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:416:14)
	at t.activateByEvent (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:646)
	at t.handleEagerExtensions (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:695:734)
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:694:950
	at Object.g [as _notify] (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at e.open (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:99:339)
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:673:320
	at Object.g [as _notify] (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at c (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:654)
	at q.then.o.(anonymous function) (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:77:868)
	at Object.g [as _notify] (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:69:572)
	at Object.enter (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (/private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:74:160)
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:286
	at /private/var/folders/g8/5crl1khn5gz63ys0j803n6y00000gn/T/AppTranslocation/3EF6205E-9063-4D49-B16C-8DAD8685F796/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:133:661
	at LOOP (fs.js:1728:14)
	at _combinedTickCallback (internal/process/next_tick.js:73:7)
	at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by miaulalala** [comment]
And thank you for taking the time analysing this, I appreciate it!

**Comment by thisboyiscrazy** [comment]
Thank that give me a direction. Can you go to "Help" > "About" and click copy. and paste it here.

```
TypeError: util_1.promisify is not a function
```

Means you are using a version of nodejs < 8.X. I will add a polyfill to fix it. But upgrade Visual Studio Code should also fix it.

**Comment by miaulalala** [comment]
```Version 1.22.2 (1.22.2)
3aeede733d9a3098f7b4bdc1f66b63b0f48c1ef9
2018-04-12T16:27:29.919Z
```

I'll update VScode and try again.

**Comment by miaulalala** [comment]
Right, there are no updates available for VSCode. Sorry, that didn't work.

**Comment by thisboyiscrazy** [comment]
Odd, the newest version is 1.30

**Comment by thisboyiscrazy** [comment]
I found the version you are running (1.22.2) but it does not seem to run correctly on my mac (10.14.3)

I can add the changes but I can not debug it. Would you be able to help me with debugging?

**Comment by miaulalala** [comment]
Yes of course, but it's going to have to wait until tomorrow unfortunately.

**Comment by thisboyiscrazy** [comment]
I actually think I have it fixed in 0.34.4 (just released) but you really should update vscode now it looks like the latest version is 1.31

**Comment by miaulalala** [comment]
Oh cool, will confirm tomorrow as well as update. What was the problem?

**Comment by thisboyiscrazy** [comment]
I was using something that was only available in nodejs 8x and up, vscode 1.22.2 uses an older version of nodejs. So I needed to add the polyfill.

**Comment by thisboyiscrazy** [comment]
@miaulalala Did you confirm it's fixed?

**Comment by miaulalala** [comment]
Hi sorry, not had a chance yet, but I'll be checking tomorrow! Thanks again for your help!

**Comment by miaulalala** [comment]
Hi @thisboyiscrazy , it works again! Thank you!
